// <auto-generated />
namespace eLections.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class EndOfElectionsNullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EndOfElectionsNullable));
        
        string IMigrationMetadata.Id
        {
            get { return "202104142234056_EndOfElectionsNullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
